name: release

on:
  push:
    branches:
      - "main" 
    tags:
      - "*" 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set VERSION variable
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          # For tag pushes, use the tag version directly
          VERSION=${GITHUB_REF/refs\/tags\//}
        else
          git fetch --tags  # Ensure all tags are fetched
        
          # Get the latest base tag (e.g., "0.1.0")
          LATEST_TAG=$(git describe --tags --abbrev=0)
        
          # Get the current week (removing any leading zero)
          WEEK=$(date +'%U')
          WEEK=$((10#$WEEK))
          YEAR=$(date +'%Y')
        
          # Build a pattern to match versions for the current week, e.g. "0.1.0-preview.2025.9.*"
          PATTERN="${LATEST_TAG}-preview.${YEAR}.${WEEK}."
        
          # Get the highest build number for this week from existing tags
          LATEST_WEEK_TAG=$(git tag -l "${PATTERN}*" | sort -V | tail -n 1)
          if [ -z "$LATEST_WEEK_TAG" ]; then
            BUILD_NUMBER=1
          else
            # Extract the build number (everything after the last dot)
            BUILD_NUMBER=${LATEST_WEEK_TAG##*.}
            BUILD_NUMBER=$((BUILD_NUMBER + 1))
          fi
        
          # Construct the version with an incremental build counter
          VERSION="${LATEST_TAG}-preview.${YEAR}.${WEEK}.${BUILD_NUMBER}"
        fi
        
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build /p:CiVersion=${VERSION} --configuration Release --no-restore

    - name: Pack
      run: dotnet pack --configuration Release --no-build --output bin

    - name: Push (allow overwriting)
      run: dotnet nuget push bin/*.nupkg --source="https://api.nuget.org/v3/index.json" --api-key ${{secrets.NUGET_API_KEY}}
