name: release

on:
  push:
    branches:
      - "main" 
    tags:
      - "*" 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set VERSION variable
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          # For tag pushes, use the tag version directly
          VERSION=${GITHUB_REF/refs\/tags\//}
        else
          git fetch --tags  # Ensure all tags are fetched
        
          # Get the latest base tag (e.g., "0.1.0")
          LATEST_TAG=$(git describe --tags --abbrev=0)
        
          # Get the current week and year (removing any leading zero from week)
          WEEK=$(date +'%U')
          WEEK=$((10#$WEEK))
          YEAR=$(date +'%Y')
        
          # Determine the start of the week (Monday). Adjust if your week starts on a different day.
          MONDAY=$(date -d "monday this week" +%Y-%m-%d)
        
          # Count the number of commits made since the start of the week
          BUILD_NUMBER=$(git rev-list --count HEAD --since="$MONDAY")
        
          # Construct the version string with the commit count as the build number
          VERSION="${LATEST_TAG}-preview.${YEAR}.${WEEK}.${BUILD_NUMBER}"
        fi
        
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build /p:CiVersion=${VERSION} --configuration Release --no-restore

    - name: Pack
      run: dotnet pack --configuration Release --no-build --output bin

    - name: Push (allow overwriting)
      run: dotnet nuget push bin/*.nupkg --source="https://api.nuget.org/v3/index.json" --api-key ${{secrets.NUGET_API_KEY}}
